repos:
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        args: ["--line-length=100"]

  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--profile=black", "--line-length=100"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: ["--fix"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        additional_dependencies: [
          "types-requests",
          "pydantic~=2.9",
          "pydantic-settings~=2.6",
        ]
        args: [
          "--config-file=pyproject.toml",
        ]

  # Optional: enable locally to run unit tests before commit
  # - repo: local
  #   hooks:
  #     - id: pytest
  #       name: pytest
  #       entry: pytest -q
  #       language: system
  #       pass_filenames: false
  #       types: [python]
